### PR TITLE
fix: fixed worker thread issue (closes #19)

### LINKED ISSUE #19: Module did not self-register
Full stack trace:

```sh
Module did not self-register: '/var/www/production/source/node_modules/node-snowball/build/Release/snowball.node'.
Error: Module did not self-register: '/var/www/production/source/node_modules/node-snowball/build/Release/snowball.node'.
   at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
   at Module.load (internal/modules/cjs/loader.js:986:32)
   at Function.Module._load (internal/modules/cjs/loader.js:879:14)
   at Module.require (internal/modules/cjs/loader.js:1026:19)
   at require (internal/modules/cjs/helpers.js:72:18)
   at Object.<anonymous> (/var/www/production/source/node_modules/node-snowball/index.js:1:16)
   at Module._compile (internal/modules/cjs/loader.js:1138:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
   at Module.load (internal/modules/cjs/loader.js:986:32)
   at Function.Module._load (internal/modules/cjs/loader.js:879:14)
   at Module.require (internal/modules/cjs/loader.js:1026:19)
   at require (internal/modules/cjs/helpers.js:72:18)
   at Object.<anonymous> (/var/www/production/source/node_modules/spamscanner/index.js:38:18)
   at Module._compile (internal/modules/cjs/loader.js:1138:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
   at Module.load (internal/modules/cjs/loader.js:986:32)
   at Function.Module._load (internal/modules/cjs/loader.js:879:14)
   at Module.require (internal/modules/cjs/loader.js:1026:19)
   at require (internal/modules/cjs/helpers.js:72:18)
   at Object.<anonymous> (/var/www/production/source/node_modules/forward-email/index.js:11:21)
   at Module._compile (internal/modules/cjs/loader.js:1138:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

### PR DESCRIPTION
**Pull request by niftylettuce**
fix: fixed worker thread issue per <https://github.com/nodejs/node/issues/21783> (closes #19)

### CODE REVIEW

**Comment by niftylettuce** [comment]
@rm-hull 👏 thank you!  can you ping me once new version is released to npm?

**Comment by rm-hull** [comment]
I've just published 0.5.0 with this in, so I guess it should show up soon on npmjs

**Comment by niftylettuce** [comment]
@rm-hull 🙇 🙇  🙇 🙇  🙇 🙇  🙇 🙇  🙇 🙇

**Comment by hthetiot** [comment]
Thank you @niftylettuce and @rm-hull

**Comment by hthetiot** [comment]
Released 0.8 with node 20 and 22+ support @niftylettuce @rm-hull 
Happy 2025

**Comment by titanism** [comment]
Haha 😆

**Pull request merged**
